# Generated by Django 4.0.4 on 2022-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubeana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('per', models.FloatField()),
                ('good_top5', models.TextField()),
                ('bad_top5', models.TextField()),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
